### ISSUE TITLE
Suppress cards for specified assets

### ISSUE THREAD

**Issue by ifringe** [mscherotter/galeryst#10]
Would it be possible to suppress the card for selected assets?

This would allow me to display informational images rather than artwork images throughout the gallery.

**Comment by mscherotter** [comment]
I have added an option as a feature for subscribers on the customize assets page:
![image](https://user-images.githubusercontent.com/641702/151097179-d61a62fa-658f-4a2a-88af-8d5150edcefc.png)
and in the Excel add-in: 
![image](https://user-images.githubusercontent.com/641702/151097304-89445d80-f3c9-4724-a353-493427382549.png)
