### ISSUE TITLE
Ordering Question

### ISSUE THREAD

**Issue by eldinor** [mscherotter/galeryst#11]
What is the way to upload photos in the desired order?
Below there are some screenshots.

1. The desired order, Lightroom. The first photo with the text should be the first in the gallery.
![image](https://user-images.githubusercontent.com/25833327/147384195-da4e779f-e805-43e4-ac8c-92305cc9c8a8.png)

2. The first photo in the gallery is the first photo by alphabet, either it is its filename (if no titles are given) or title (tried both variants).
![image](https://user-images.githubusercontent.com/25833327/147384233-8b4eca58-e9e4-4765-bbb1-74bebec9683d.png)

**Comment by mscherotter** [comment]
The image for the gallery wing is set in Lightroom.

1. Open the album in lightroom that the wing is using for imagery
2. Right click on the image you want to use for the wing's image in the foyer.
3. Select **Set as album cover**
4. Customize your gallery and re-generate it.

https://galeryst.com/tutorial/settingCoverPhoto
