### ISSUE TITLE
Text is not displayed completely, the right border of the text box in the foyer gets cut of somehow.

### ISSUE THREAD

**Issue by DigitalJens** [mscherotter/galeryst#15]
**Describe the bug**
See title

**To Reproduce**
'just go to the foyer and try to display longer texts'

**Screenshots**
See attached

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser Chrome
 - Version 97.0.4692.71

**Additional context**
![Foyertext_cut_of](https://user-images.githubusercontent.com/41649441/149411961-89fc32d5-5352-480f-a0dd-cdbe4e6310b3.png)

**Comment by mscherotter** [comment]
This has just been fixed, refresh the page (F5) the next time you go to it and try again.  Please report back.

**Comment by mscherotter** [comment]
This has just been fixed, refresh the page (F5) the next time you go to it and try again.  Please report back.

**Comment by mscherotter** [comment]
Fixed on 1/13/2022
