### ISSUE TITLE
When switching back to the foyer by the lower left "location-menu" the foyer text is not shown any more.

### ISSUE THREAD

**Issue by DigitalJens** [mscherotter/galeryst#16]
**Describe the bug**
See title

**To Reproduce**
1. Go from foyer to gallery by left clicking the foyer artwork. Note that the texts in the foyer as well as in the gallery beside the single pictures is displayed in the right way.
2. From the gallery go back to the foyer by selecting "foyer" in the lower left location selector. Note that the foyer text isn't displayed any more.
3. If you now select gallery again, note that the text beside the pictures isn't displaye correctly any more. There are just black boxes.
For some reason, I can't reproduce this last point anymore for taking a screenshot.

**Expected behavior**
Correctly displayed text even if you switch back and forward.

**Screenshots**
see attached

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser Chrome
 - Version 97.0.4692.71

**Additional context**
![Text_missing_foyer](https://user-images.githubusercontent.com/41649441/149413154-6ee8a57a-88bf-456c-92da-35fc86de20a1.png)

**Comment by mscherotter** [comment]
Fixed on 1/13/2022

**Comment by DigitalJens** [comment]
Yes - thank you!
