### ISSUE TITLE
Add outer walls to the icons beside the wing layout names and provide the total number of possible artworks

### ISSUE THREAD

**Issue by DigitalJens** [mscherotter/galeryst#17]
Hi Micheal,

from a usability perspective I think it would be better to also show the outer walls on the small icons beside the layout name (wings) and provide the total number of artworks which are possible with this layout. It took a while to understand the logic behind and that "none" could be one of the most interesting for me.

Best regards

Jens

**Comment by mscherotter** [comment]
How is this?
![image](https://user-images.githubusercontent.com/641702/149679781-378c094b-a132-4b78-bb93-1bb96b1c9a02.png)

**Comment by DigitalJens** [comment]
Micheal, that's great and much more understandable imo.
