### ISSUE TITLE
Gallery Visitor Analytics

### ISSUE THREAD

**Issue by DigitalJens** [mscherotter/galeryst#20]
Later on, it would be great to have something like a Visitor Counter, in order to see, if the effort building a gallery is worth it. Addionally in a similar way a picture view counter would be great to see, which pictures are the less clicked (and therefore less impressive) which could be replaced.
Maybe Google Analytics can be integrated somehow?

Best regards

Jens

**Comment by mscherotter** [comment]
Split off #23 to its own feature.

**Comment by mscherotter** [comment]
Implemented Visit and Visitor counter on Gallery page
![image](https://user-images.githubusercontent.com/641702/149713628-844f106b-bf10-4381-9a91-cbbc01f124a9.png)

**Comment by DigitalJens** [comment]
Great, thank you for providing this feature in such a short time!
