### ISSUE TITLE
Additional room layouts

### ISSUE THREAD

**Issue by DigitalJens** [mscherotter/galeryst#22]
Hi Micheal,

I want to suggest two room layouts with just one additional wall lengthwise to the room.

For the first one the path you can walk looks like an "0". For the second one the wall is touching one of the outer walls so that the path you can walk through looks like an "U". Of course the amount of additional artwork you can hang on one single wall is not too much. However the room would have a lot of space to breath, while maintaining orientation at the same time.

Best regards

Jens

**Comment by mscherotter** [comment]
Jens - can you please include a graphic of what each layout would look like for clarity?

**Comment by DigitalJens** [comment]
Sure - see attached

![Layouts](https://user-images.githubusercontent.com/41649441/150197013-0c7451d1-523b-423e-a7e8-5afd2dac9b5f.png)

**Comment by mscherotter** [comment]
Additional room layouts have been added:
![image](https://user-images.githubusercontent.com/641702/150236884-429a1a1f-aee4-42b4-b9f8-45e2d48575ff.png)

**Comment by DigitalJens** [comment]
Great! Thank you for such a fast implementation!
