### ISSUE TITLE
Deleted keywords in Lightroom remain on the cards beside the pictures

### ISSUE THREAD

**Issue by DigitalJens** [mscherotter/galeryst#24]
**Describe the bug**
Deleted keywords in Lightroom remain on the cards beside the pictures

**To Reproduce**
1. Add "subject" in card template
2. Add a keyword in LR
3. Update gallery
4. See how keyword is being displayed on the card
5. Now remove the keyword in LR
6. Update gallery
7. See how keyword is still displayed

**Expected behavior**
I would expect, that the keyword isn't displayed anymore after deletion in LR and after rebuilding the gallery.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 97.0.4692.99

**Comment by mscherotter** [comment]
the subject in the card template has been deprecated - it is no longer supported.

**Comment by DigitalJens** [comment]
I see. Great that you deleted it in your property descriptions.
