### ISSUE TITLE
Less detailed time format for the capture date

### ISSUE THREAD

**Issue by DigitalJens** [mscherotter/galeryst#25]
The {{captureDateString}} property is displayed quite detailed on the cards.
Instead of "Sat Jan 22 2022" just "Jan 2022" or even "January 2022" could be enought for many.
Maybe different formats could be displayed by choosing between different property names. Here an example:
- captureDateString (already existing and for keeping existing galleries working)
- captureDateStringMMMYYYY
- captureDateStringMMMMYYYY

Best regards

Jens

**Comment by mscherotter** [comment]
captureDateStringMMMYYYY and captureDateStringMMMMYYYY have been added as requested.

**Comment by DigitalJens** [comment]
Great - thank you so much! I really appreciate, that you implement things faster than I could test :-).
