### ISSUE TITLE
2D Card Design

### ISSUE THREAD

**Issue by ifringe** [mscherotter/galeryst#31]
Thank you for allowing for the customization of the card next to the artwork.

Can we also have the ability to customize the 2D card that appears when clicking the info icon? There is specific information, such as the date, that I wish to suppress.

**Comment by mscherotter** [comment]
Do you want the same design for the 2D card as the 3D card?

**Comment by ifringe** [comment]
Do you mean the same options? That would be pretty cool, since artists could really customize the two cards.

david

**Comment by mscherotter** [comment]
I'd like to keep them the same - to reduce complexity.

**Comment by ifringe** [comment]
That works, too!

david

**Comment by mscherotter** [comment]
This has been completed.
