### ISSUE TITLE
Wing Cover Photo and more Control over Wing Photo Order

### ISSUE THREAD

**Issue by edpuskas** [mscherotter/galeryst#34]
**Is your feature request related to a problem? Please describe.**
I love the new Gallery Cover Photo option. It would be beneficial to also be able to Wing Cover photos. Currently it seems to pick randomly the photo it uses as a cover to represent each Wing.

**Describe the solution you'd like**
Ability to upload a photo for Wing cover just like we now can for the Gallery Cover.
Also it may just be my misunderstanding of how photos are displayed in wings, but I would like the ability to change the order they appear. 

**Describe alternatives you've considered**
Ability to use the camera feature to change a Wing Cover, as well as the ability to upload a photo for a Wing Cover.

**Additional context**
Appreciate the new features, would also appreciate an explanation of controlling the order of how photos are displayed in a wing. Thanks let me know if u need more info.

**Comment by mscherotter** [comment]
1. The Wing cover photo is picked in Lightroom as the album cover.  In Lightroom, right click on an image in  the strip and select the "Set as Album Cover" option.
2. The order of the images in a wing is determined by the order of the images in the Lightroom album.  clockwise around the outside wall starting with 6:00 and then the interior panels left to right.

**Comment by edpuskas** [comment]
Thanks Michael! That indeed worked, my problem was that I normally use the full Lightroom CC, not a fan of the web version but sure enough by using the web version it took care of my problems. Sorry please close it was indeed my fault.
