### ISSUE TITLE
Request to follow me button (Teams)

### ISSUE THREAD

**Issue by ryanbliss** [mscherotter/galeryst#50]
**Is your feature request related to a problem? Please describe.**
Hard to know how many people are following me and request that people follow me. Not everyone could grok that as host, people would be prompted to follow them, so adding visibility & control would be useful.

**Describe the solution you'd like**
Would be nice to request people to follow me, see how many people are following me, etc. This also came up as a request from attendee POV.

**Comment by mscherotter** [comment]
Added this to the host pane in the upper left.
![image](https://user-images.githubusercontent.com/641702/223921692-b02d7b89-79d4-4237-adb6-cecb7785d49f.png)
