### ISSUE TITLE
Alert/Toast notification to 'follow'someone covers UI

### ISSUE THREAD

**Issue by corinagum** [mscherotter/galeryst#51]
Hey! AWESOME APP

## Bug report
**Describe the bug**

When another user shares an artwork to follow, the toast/alert  blocks the UI:
![image](https://user-images.githubusercontent.com/14900841/223824584-37eaad44-beaf-4704-924a-740f230d1ac1.png)

**To Reproduce**
1. Foyer or gallery wing (happens in both)
2. Wait for host to share an artwork
3. Notice that user must press x on the toast or follow the presenter -- user cannot continue to use menu independently

**Expected behavior**
User should be able to follow user using toast notification, or ignore toast and continue to navigate independently

**Screenshots**
![image](https://user-images.githubusercontent.com/14900841/223825029-baa9541c-1318-42c2-9d93-1d3ed7ebcc60.png)
Can't change wings or use settings button without clicking X button first.

**Desktop (please complete the following information):**
 - MacOS (Ventura)
 - Teams Desktop
 - Version -- don't know, sorry. This was with Ryan Bliss who did a presentation of the app 🙂 

**Additional context**
This is just a friendly suggestion, but perhaps instead of having a long rectangle for showing the (orange) UI, a popover that shows up above the menu would be cool.  The popover could appear over a 'notification' icon with a (!) badge that appears when there's been new activity.  I'll stop before I get carried away

non-customized example from fluent: 
![image](https://user-images.githubusercontent.com/14900841/223828841-e022b9ea-82cd-4079-bf1c-12f0091d638b.png)

-------

## Mini bug?
Also, this doesn't warrant an entire new bug, but when I looked up I saw:
![image](https://user-images.githubusercontent.com/14900841/223825873-199892dc-71a2-440c-b5eb-1dce6418b306.png)

I thought I would point it out in case it's something you would want to get rid of 🙂

**Comment by mscherotter** [comment]
@corinagum  you found a light ;) 💡
