### ISSUE TITLE
Add support for narration and music bed

### ISSUE THREAD

**Issue by ifringe** [mscherotter/galeryst#6]
Please add support for:

-- Narration. It seems like adding a narration button/icon/something to the card would be an ideal solution to let the user play sound files that I have previously uploaded. This means, of course, we need the ability to upload asset-specific sound files.

-- Ambient music/music bed. It would be ideal to add a music bed to the gallery and even better, each wing (if desired, otherwise, the default gallery music bed plays). Ideally, if narration is invoked the music bed is ducked while the narration is playing.

**Comment by mscherotter** [comment]
This is now implemented in Tours.
https://blog.galeryst.com/tutorials/gallery-tours/
