### ISSUE TITLE
Guidelines/Tour

### ISSUE THREAD

**Issue by ifringe** [mscherotter/galeryst#7]
It would be nice if I could create a guideline, or tour, that automatically guides the user through the gallery/wing. This predefined tour would let me highlight the most important pieces of artwork. 

In addition, tour narration would enhance the experience as well, again through a sound file I uploaded. This would imply that timing would have to set in the guideline, including stop and move timing.

**Comment by mscherotter** [comment]
Tours are now in Galeryst
https://blog.galeryst.com/tutorials/gallery-tours/
