### ISSUE TITLE
Custom Cover Image Upload

### ISSUE THREAD

**Issue by ifringe** [mscherotter/galeryst#8]
I see how you can set a custom cover image by taking a photo of the gallery.

I would like, instead, to upload my own custom cover image.

**Comment by mscherotter** [comment]
This is now an option for Galeryst subscribers when you customize a gallery.

![GalleryCover](https://user-images.githubusercontent.com/641702/152445497-eb866d61-2a72-493d-8c22-fc3506c1de06.gif)
