### ISSUE TITLE
Logo Display

### ISSUE THREAD

**Issue by ifringe** [mscherotter/galeryst#9]
It would be nice to allow me to upload/set/feature my logos, including a gallery-level logo and a wing-level logo.

**Comment by mscherotter** [comment]
How would you want to see the logos?  Can you give an example or mock-up?

**Comment by ifringe** [comment]
Hello!

Thank you for working on the GitHub list!

Here’s two high quality mock ups showing what we could do with the logo. I spent hours and hours, days if not weeks creating these mock ups. Or, less than 5 minutes, LOL

Notice how I titled my show, too, LOL?

david

**Comment by mscherotter** [comment]
Can you include the mock-up images?

**Comment by ifringe** [comment]
Here are two potential mock ups.
![Mock Up 1](https://user-images.githubusercontent.com/1482478/151218385-82b6d2a5-fde8-439c-8591-ba278a360304.jpg)
![Mock Up 2](https://user-images.githubusercontent.com/1482478/151218390-0042e16a-ec13-4989-8c62-b18474a75873.jpg)

**Comment by mscherotter** [comment]
Looks great!  Thanks for sharing.

**Comment by mscherotter** [comment]
This feature is now enabled for subscribers with custom Foyer Titles.  

Images can be hosted on the free image hosting service [imgur.com](https://imgur.com)

![image](https://user-images.githubusercontent.com/641702/152692961-f96435de-7620-43e1-8afc-18c3aa54a7df.png)
